version: "3.3"
services:
  app:
    image: ruby:alpine
    volumes:
      - .:/app
    depends_on:
      - arelle
      - validator
  
  validator:
    image: seocahill/xbrl-validator
    ports:
      - "4567:4567"
    volumes: 
      - ./ixbrl:/ixbrl
    entrypoint: jruby
    command: /app/app.rb

  arelle:
    image: seocahill/arelle:latest
    ports:
      - "8080:8080"
    volumes: 
      - ./ixbrl:/ixbrl